version: '3'

services:
  db:
    image: postgres:14.7
    # volumes:
    #   - "../docker-data/psql-data:/var/lib/postgresql/data"
    # container_name: captionlive_db_traefik
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=114514
    
  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   depends_on:
  #     - db
  #   volumes:
  #     - "../docker-data/pga4-data:/var/lib/pgadmin"
  #   ports:
  #     - "800:80"
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
  #     - PGADMIN_DEFAULT_PASSWORD=admin
  #   container_name: captionlive_pgadmin_traefik

  api:
    image: lijiaxi2018/cl_api_prod
    # volumes:
    #   - "../docker-data/files:/app/files"
    # restart: unless-stopped
    depends_on:
      - db
    # container_name: captionlive_api_traefik
    ports:
      - "8080:8080"

  frontend:
    image: lijiaxi2018/cl_frontend_dev_nginx
    # container_name: captionlive_frontend_traefik
    ports:
      - "80:80"